version: '3.1'
services:
  kibana:
    build:
      context: ./
    container_name: kibana
    volumes:
      - ./data:/usr/share/kibana/data
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    restart: always
