version: '3.1'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    container_name: kibana
    volumes:
      - ./data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://docker.for.mac.localhost:9200
