version: '3.1'
services:
  db:
    image: mysql:8.0.21
    container_name: rudeo_mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rudeo512
      - MYSQL_USER=caru
      - MYSQL_PASSWORD=rudeo512