version: '3.1'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.1
    container_name: logstash
    volumes:
      - ./data:/usr/share/logstash/data
      - ./config:/usr/share/logstash/config:ro
    ports:
      - 9600:9600
