version: '3.1'
services:
  logstash:
    build:
      context: ./
    container_name: logstash
    volumes:
      - ./data:/usr/share/logstash/data
      - ./config:/usr/share/logstash/config:ro
    ports:
      - 9600:9600
