filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '../../kafka/kafka_2.12-2.0.1/logs/server.log'
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after
    fields.pipeline: kafka-logs

#========== KAFKA output
output.kafka:
  hosts: ['localhost:9092', 'localhost:9093', 'localhost:9094']
  topic: 'peter-log'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000